DROP TABLE IF EXISTS "words" CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS "books" CASCADE;
--> statement-breakpoint
CREATE TABLE "books" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"word_count" integer DEFAULT 0 NOT NULL,
	"cover_url" text,
	"book_id" varchar(100) NOT NULL,
	"tags" text,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"stage" varchar(20) DEFAULT '小学' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "books_book_id_unique" UNIQUE("book_id")
);
--> statement-breakpoint
CREATE TABLE "words" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"word_rank" integer,
	"head_word" varchar(255),
	"content" json,
	"book_id" varchar(100) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "words_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("book_id") ON DELETE CASCADE
);
--> statement-breakpoint
CREATE INDEX "words_book_id_idx" ON "words" USING btree ("book_id");