import { eq, and, asc, desc, sql } from 'drizzle-orm';
import { genSaltSync, hashSync } from 'bcrypt-ts';
import { users, books, words, userBookProgress, userWordProgress } from '../lib/schema';
import { db, client } from '../lib/db';

// ============================================================
// 表自动创建
// ============================================================

async function ensureUserTableExists() {
  const result = await client`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name = 'User'
    );`;

  if (!result[0].exists) {
    await client`
      CREATE TABLE "User" (
        id SERIAL PRIMARY KEY,
        email VARCHAR(64),
        password VARCHAR(64)
      );`;
  }
}

async function ensureUserProgressTablesExist() {
  await client`CREATE TABLE IF NOT EXISTS "user_book_progress" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES "public"."User"("id") ON DELETE CASCADE,
    book_id VARCHAR(100) NOT NULL REFERENCES "public"."books"("book_id") ON DELETE CASCADE,
    current_word_index INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT "user_book_progress_user_book_unique" UNIQUE("user_id", "book_id")
  )`;
  await client`CREATE INDEX IF NOT EXISTS "user_book_progress_user_id_idx" ON "user_book_progress" ("user_id")`;
  await client`CREATE TABLE IF NOT EXISTS "user_word_progress" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL REFERENCES "public"."User"("id") ON DELETE CASCADE,
    word_id BIGINT NOT NULL REFERENCES "public"."words"("id") ON DELETE CASCADE,
    book_id VARCHAR(100) NOT NULL REFERENCES "public"."books"("book_id") ON DELETE CASCADE,
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT "user_word_progress_user_word_unique" UNIQUE("user_id", "word_id")
  )`;
  await client`CREATE INDEX IF NOT EXISTS "user_word_progress_user_book_idx" ON "user_word_progress" ("user_id", "book_id")`;
  await client`
    DO $$
    BEGIN
      IF to_regclass('public.study_progress') IS NOT NULL THEN
        INSERT INTO "user_book_progress" ("user_id", "book_id", "current_word_index", "updated_at")
        SELECT "user_id", "book_id", "current_word_index", "updated_at"
        FROM "study_progress"
        ON CONFLICT ("user_id", "book_id") DO NOTHING;
      END IF;
    END $$;
  `;
}

let initialized = false;

async function initDatabase() {
  if (initialized) return;
  await ensureUserTableExists();
  await ensureUserProgressTablesExist();
  initialized = true;
}

// ============================================================
// User 操作
// ============================================================

export async function getUser(email: string) {
  await initDatabase();
  return await db.select().from(users).where(eq(users.email, email));
}

export async function createUser(email: string, password: string) {
  await initDatabase();
  const salt = genSaltSync(10);
  const hash = hashSync(password, salt);
  return await db.insert(users).values({ email, password: hash });
}

// ============================================================
// Books 操作
// ============================================================

export async function getBooks() {
  await initDatabase();
  return await db
    .select()
    .from(books)
    .where(eq(books.status, 'active'))
    .orderBy(asc(books.id));
}

export async function getBookById(bookId: string) {
  await initDatabase();
  const result = await db
    .select()
    .from(books)
    .where(eq(books.bookId, bookId))
    .limit(1);
  return result[0] ?? null;
}

// ============================================================
// Words 操作
// ============================================================

export async function getWordsByBook(
  bookId: string,
  start: number = 0,
  limit: number = 20,
) {
  await initDatabase();
  return await db
    .select()
    .from(words)
    .where(eq(words.bookId, bookId))
    .orderBy(asc(words.wordRank))
    .offset(start)
    .limit(limit);
}

export async function getWordById(wordId: number) {
  await initDatabase();
  const result = await db
    .select()
    .from(words)
    .where(eq(words.id, wordId))
    .limit(1);
  return result[0] ?? null;
}

export async function getWordCountByBook(bookId: string) {
  await initDatabase();
  const result = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(words)
    .where(eq(words.bookId, bookId));
  return result[0]?.count ?? 0;
}

// ============================================================
// StudyProgress 操作
// ============================================================

export async function getProgress(userId: number, bookId: string) {
  await initDatabase();
  const result = await db
    .select()
    .from(userBookProgress)
    .where(
      and(eq(userBookProgress.userId, userId), eq(userBookProgress.bookId, bookId)),
    )
    .limit(1);
  return result[0] ?? null;
}

export async function getAllProgress(userId: number) {
  await initDatabase();
  return await db
    .select({
      bookId: books.bookId,
      currentWordIndex: sql<number>`coalesce(${userBookProgress.currentWordIndex}, 0)::int`,
      updatedAt: userBookProgress.updatedAt,
      bookTitle: books.title,
      wordCount: books.wordCount,
    })
    .from(books)
    .leftJoin(
      userBookProgress,
      and(
        eq(userBookProgress.bookId, books.bookId),
        eq(userBookProgress.userId, userId),
      ),
    )
    .where(eq(books.status, 'active'))
    .orderBy(asc(books.id));
}

// ============================================================
// 学习计划操作
// ============================================================

export async function addBookToPlan(userId: number, bookId: string) {
  await initDatabase();
  await db
    .insert(userBookProgress)
    .values({ userId, bookId, currentWordIndex: 0 })
    .onConflictDoNothing({
      target: [userBookProgress.userId, userBookProgress.bookId],
    });
}

export async function removeBookFromPlan(userId: number, bookId: string) {
  await initDatabase();
  await db
    .delete(userBookProgress)
    .where(
      and(eq(userBookProgress.userId, userId), eq(userBookProgress.bookId, bookId)),
    );
}

export async function getUserPlanBooks(userId: number) {
  await initDatabase();
  return await db
    .select({
      bookId: books.bookId,
      title: books.title,
      wordCount: books.wordCount,
      coverUrl: books.coverUrl,
      currentWordIndex: sql<number>`coalesce(${userBookProgress.currentWordIndex}, 0)::int`,
      updatedAt: userBookProgress.updatedAt,
    })
    .from(books)
    .innerJoin(
      userBookProgress,
      and(
        eq(userBookProgress.bookId, books.bookId),
        eq(userBookProgress.userId, userId),
      ),
    )
    .where(eq(books.status, 'active'))
    .orderBy(asc(books.id));
}

export async function upsertProgress(
  userId: number,
  bookId: string,
  currentWordIndex: number,
  wordId?: number,
) {
  await initDatabase();
  await db
    .insert(userBookProgress)
    .values({ userId, bookId, currentWordIndex })
    .onConflictDoUpdate({
      target: [userBookProgress.userId, userBookProgress.bookId],
      set: {
        currentWordIndex,
        updatedAt: sql`now()`,
      },
    });

  if (wordId != null) {
    await db
      .insert(userWordProgress)
      .values({ userId, bookId, wordId, lastSeenAt: new Date() })
      .onConflictDoUpdate({
        target: [userWordProgress.userId, userWordProgress.wordId],
        set: { bookId, lastSeenAt: sql`now()` },
      });
  }
}