import { eq, and, asc, sql } from 'drizzle-orm';
import { genSaltSync, hashSync } from 'bcrypt-ts';
import { users, books, words, studyProgress } from '../lib/schema';
import { db, client } from '../lib/db';

// ============================================================
// 表自动创建
// ============================================================

async function ensureUserTableExists() {
  const result = await client`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name = 'User'
    );`;

  if (!result[0].exists) {
    await client`
      CREATE TABLE "User" (
        id SERIAL PRIMARY KEY,
        email VARCHAR(64),
        password VARCHAR(64)
      );`;
  }
}

async function ensureStudyProgressTableExists() {
  const result = await client`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_name = 'study_progress'
    );`;

  if (!result[0].exists) {
    await client`
      CREATE TABLE "study_progress" (
        id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id            INTEGER NOT NULL REFERENCES "public"."User"("id") ON DELETE CASCADE,
        book_id            VARCHAR(100) NOT NULL REFERENCES "public"."books"("book_id") ON DELETE CASCADE,
        current_word_index INTEGER NOT NULL DEFAULT 0,
        created_at         TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        updated_at         TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
        CONSTRAINT "study_progress_user_book_unique" UNIQUE("user_id", "book_id")
      );`;

    await client`
      CREATE INDEX "study_progress_user_id_idx" ON "study_progress" USING btree ("user_id");`;
  }
}

let initialized = false;

async function initDatabase() {
  if (initialized) return;
  await ensureUserTableExists();
  await ensureStudyProgressTableExists();
  initialized = true;
}

// ============================================================
// User 操作
// ============================================================

export async function getUser(email: string) {
  await initDatabase();
  return await db.select().from(users).where(eq(users.email, email));
}

export async function createUser(email: string, password: string) {
  await initDatabase();
  const salt = genSaltSync(10);
  const hash = hashSync(password, salt);
  return await db.insert(users).values({ email, password: hash });
}

// ============================================================
// Books 操作
// ============================================================

export async function getBooks() {
  await initDatabase();
  return await db
    .select()
    .from(books)
    .where(eq(books.status, 'active'))
    .orderBy(asc(books.id));
}

export async function getBookById(bookId: string) {
  await initDatabase();
  const result = await db
    .select()
    .from(books)
    .where(eq(books.bookId, bookId))
    .limit(1);
  return result[0] ?? null;
}

// ============================================================
// Words 操作
// ============================================================

export async function getWordsByBook(
  bookId: string,
  start: number = 0,
  limit: number = 20,
) {
  await initDatabase();
  return await db
    .select()
    .from(words)
    .where(eq(words.bookId, bookId))
    .orderBy(asc(words.wordRank))
    .offset(start)
    .limit(limit);
}

export async function getWordById(wordId: number) {
  await initDatabase();
  const result = await db
    .select()
    .from(words)
    .where(eq(words.id, wordId))
    .limit(1);
  return result[0] ?? null;
}

export async function getWordCountByBook(bookId: string) {
  await initDatabase();
  const result = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(words)
    .where(eq(words.bookId, bookId));
  return result[0]?.count ?? 0;
}

// ============================================================
// StudyProgress 操作
// ============================================================

export async function getProgress(userId: number, bookId: string) {
  await initDatabase();
  const result = await db
    .select()
    .from(studyProgress)
    .where(
      and(eq(studyProgress.userId, userId), eq(studyProgress.bookId, bookId)),
    )
    .limit(1);
  return result[0] ?? null;
}

export async function getAllProgress(userId: number) {
  await initDatabase();
  return await db
    .select({
      bookId: studyProgress.bookId,
      currentWordIndex: studyProgress.currentWordIndex,
      updatedAt: studyProgress.updatedAt,
      bookTitle: books.title,
      wordCount: books.wordCount,
    })
    .from(studyProgress)
    .leftJoin(books, eq(studyProgress.bookId, books.bookId))
    .where(eq(studyProgress.userId, userId));
}

export async function upsertProgress(
  userId: number,
  bookId: string,
  currentWordIndex: number,
) {
  await initDatabase();
  await db
    .insert(studyProgress)
    .values({ userId, bookId, currentWordIndex })
    .onConflictDoUpdate({
      target: [studyProgress.userId, studyProgress.bookId],
      set: {
        currentWordIndex,
        updatedAt: sql`now()`,
      },
    });
}